START TRANSACTION;

DROP DATABASE IF EXISTS att;
CREATE DATABASE att;
USE att;


DROP TABLE IF EXISTS `admin`;
CREATE TABLE `admin` (
    `id` INT(10) NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL
    PRIMARY KEY (`id`)
)ENGINE=MariaDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


COMMIT;